-- MySQL Script generated by MySQL Workbench
-- Sat 23 Sep 2017 05:36:22 PM MYT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zangetsu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zangetsu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zangetsu` DEFAULT CHARACTER SET utf8 ;
USE `zangetsu` ;

-- -----------------------------------------------------
-- Table `zangetsu`.`commit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zangetsu`.`commit` (
  `commitID` INT(11) NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`commitID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zangetsu`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zangetsu`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `zangetsu`.`commit_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zangetsu`.`commit_user` (
  `commit_userID` INT(11) NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NOT NULL,
  `commitID` INT(11) NOT NULL,
  PRIMARY KEY (`commit_userID`),
  INDEX `userID_fk_idx` (`userID` ASC),
  INDEX `commitID_fk_idx` (`commitID` ASC),
  CONSTRAINT `commitID_fk`
    FOREIGN KEY (`commitID`)
    REFERENCES `zangetsu`.`commit` (`commitID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userID_fk`
    FOREIGN KEY (`userID`)
    REFERENCES `zangetsu`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zangetsu`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zangetsu`.`room` (
  `roomID` INT(11) NOT NULL AUTO_INCREMENT,
  `ownerID` INT(11) NOT NULL DEFAULT '0',
  `roomName` VARCHAR(45) NOT NULL DEFAULT 'default',
  PRIMARY KEY (`roomID`),
  INDEX `fk_ownerID_idx` (`ownerID` ASC),
  CONSTRAINT `fk_ownerID`
    FOREIGN KEY (`ownerID`)
    REFERENCES `zangetsu`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zangetsu`.`room_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zangetsu`.`room_user` (
  `room_userID` INT(11) NOT NULL AUTO_INCREMENT,
  `roomID` INT(11) NOT NULL DEFAULT '0',
  `userID` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`room_userID`),
  INDEX `fk_roomID_idx` (`roomID` ASC),
  INDEX `fk_userID_idx` (`userID` ASC),
  CONSTRAINT `fk_roomID`
    FOREIGN KEY (`roomID`)
    REFERENCES `zangetsu`.`room` (`roomID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `zangetsu`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zangetsu`.`user_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zangetsu`.`user_data` (
  `userdataID` INT(11) NOT NULL DEFAULT '0',
  `verified` INT(11) NOT NULL DEFAULT '0',
  `hash` VARCHAR(255) NOT NULL DEFAULT '0',
  PRIMARY KEY (`userdataID`),
  CONSTRAINT `fk_user_data_1`
    FOREIGN KEY (`userdataID`)
    REFERENCES `zangetsu`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
